//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shared.Resources.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please accept Terms &amp; Conditions..
        /// </summary>
        public static string AcceptTermAndConditons {
            get {
                return ResourceManager.GetString("AcceptTermAndConditons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is required..
        /// </summary>
        public static string AccessTokenRequired {
            get {
                return ResourceManager.GetString("AccessTokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account type is required..
        /// </summary>
        public static string AccountTypeRequired {
            get {
                return ResourceManager.GetString("AccountTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to activate this escort account..
        /// </summary>
        public static string ActivateEscort {
            get {
                return ResourceManager.GetString("ActivateEscort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to activate this establishment account..
        /// </summary>
        public static string ActivateEstablishment {
            get {
                return ResourceManager.GetString("ActivateEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to activate this user account..
        /// </summary>
        public static string ActivateUser {
            get {
                return ResourceManager.GetString("ActivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) activated ##TargetUserName## (##TargetUserRole##) profile.
        /// </summary>
        public static string AdminUserActivateProfile {
            get {
                return ResourceManager.GetString("AdminUserActivateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) approved ##TargetUserName## (##TargetUserRole##) profile.
        /// </summary>
        public static string AdminUserApproveProfile {
            get {
                return ResourceManager.GetString("AdminUserApproveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) created ##TargetUserName## (##TargetUserRole##) profile.
        /// </summary>
        public static string AdminUserCreateProfile {
            get {
                return ResourceManager.GetString("AdminUserCreateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) deactivated ##TargetUserName## (##TargetUserRole##) profile.
        /// </summary>
        public static string AdminUserDeActivateProfile {
            get {
                return ResourceManager.GetString("AdminUserDeActivateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) denied ##TargetUserName## (##TargetUserRole##) profile.
        /// </summary>
        public static string AdminUserDeniedProfile {
            get {
                return ResourceManager.GetString("AdminUserDeniedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) export ##TargetUserName## (##TargetUserRole##) balance report.
        /// </summary>
        public static string AdminUserExportClientBalanceReport {
            get {
                return ResourceManager.GetString("AdminUserExportClientBalanceReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) export payment report.
        /// </summary>
        public static string AdminUserExportPaymentReport {
            get {
                return ResourceManager.GetString("AdminUserExportPaymentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) mark payment done for ##TargetUserName## (##TargetUserRole##).
        /// </summary>
        public static string AdminUserMarkPaymentDone {
            get {
                return ResourceManager.GetString("AdminUserMarkPaymentDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##AdminUserName## (##AdminUserRole##) updated ##TargetUserName## (##TargetUserRole##) profile.
        /// </summary>
        public static string AdminUserUpdateProfile {
            get {
                return ResourceManager.GetString("AdminUserUpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update subscription..
        /// </summary>
        public static string AjaxErrorUpdateSubscription {
            get {
                return ResourceManager.GetString("AjaxErrorUpdateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged into another device..
        /// </summary>
        public static string AnotherDeviceLogin {
            get {
                return ResourceManager.GetString("AnotherDeviceLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile approved successfully..
        /// </summary>
        public static string ApproveProfile {
            get {
                return ResourceManager.GetString("ApproveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version is required..
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account holder name is required..
        /// </summary>
        public static string BankAccountHolderNameRequired {
            get {
                return ResourceManager.GetString("BankAccountHolderNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank account number is required..
        /// </summary>
        public static string BankAccountNumberRequired {
            get {
                return ResourceManager.GetString("BankAccountNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank details update failed..
        /// </summary>
        public static string BankDetailUpdateFailed {
            get {
                return ResourceManager.GetString("BankDetailUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank details updated successfully..
        /// </summary>
        public static string BankDetailUpdateSuccess {
            get {
                return ResourceManager.GetString("BankDetailUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank name is required..
        /// </summary>
        public static string BankNameRequired {
            get {
                return ResourceManager.GetString("BankNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSB code is required..
        /// </summary>
        public static string BSBNumberRequired {
            get {
                return ResourceManager.GetString("BSBNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission denied. You cannot open the camera..
        /// </summary>
        public static string cameraDenied {
            get {
                return ResourceManager.GetString("cameraDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera permission granted..
        /// </summary>
        public static string cameraGranted {
            get {
                return ResourceManager.GetString("cameraGranted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please attach a camera device and refresh the page to access the camera..
        /// </summary>
        public static string cameraNotDetected {
            get {
                return ResourceManager.GetString("cameraNotDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password is required..
        /// </summary>
        public static string ConfirmPasswordRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password and Confirm Password must be same..
        /// </summary>
        public static string ConfirmPasswordValid {
            get {
                return ResourceManager.GetString("ConfirmPasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your query has been sent to support. Our support team will contact you soon..
        /// </summary>
        public static string ContactUsMailSuccess {
            get {
                return ResourceManager.GetString("ContactUsMailSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUsSubject {
            get {
                return ResourceManager.GetString("ContactUsSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit payment failed.
        /// </summary>
        public static string CreditPaymentFailed {
            get {
                return ResourceManager.GetString("CreditPaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit payment successfull.
        /// </summary>
        public static string CreditPaymentSuccess {
            get {
                return ResourceManager.GetString("CreditPaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to deactivate this escort account..
        /// </summary>
        public static string DeactivateEscort {
            get {
                return ResourceManager.GetString("DeactivateEscort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to deactivate this establishment account..
        /// </summary>
        public static string DeactivateEstablishment {
            get {
                return ResourceManager.GetString("DeactivateEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to deactivate this user account..
        /// </summary>
        public static string DeactivateUser {
            get {
                return ResourceManager.GetString("DeactivateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete this escort account..
        /// </summary>
        public static string DeleteEscort {
            get {
                return ResourceManager.GetString("DeleteEscort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete this establishment account..
        /// </summary>
        public static string DeleteEstablishment {
            get {
                return ResourceManager.GetString("DeleteEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to delete this user account..
        /// </summary>
        public static string DeleteUser {
            get {
                return ResourceManager.GetString("DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile denied successfully..
        /// </summary>
        public static string DeniedProfile {
            get {
                return ResourceManager.GetString("DeniedProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required..
        /// </summary>
        public static string DisplayNameRequired {
            get {
                return ResourceManager.GetString("DisplayNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email already verified..
        /// </summary>
        public static string EmailAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification successful..
        /// </summary>
        public static string EmailCodeVerified {
            get {
                return ResourceManager.GetString("EmailCodeVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address already exists..
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email length should be maximum 100 characters..
        /// </summary>
        public static string EmailLength {
            get {
                return ResourceManager.GetString("EmailLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not verified..
        /// </summary>
        public static string EmailNotVerified {
            get {
                return ResourceManager.GetString("EmailNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid email..
        /// </summary>
        public static string EmailValid {
            get {
                return ResourceManager.GetString("EmailValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification successful. Please proceed with your login..
        /// </summary>
        public static string EmailVerified {
            get {
                return ResourceManager.GetString("EmailVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on enable button to give the camera permission.
        /// </summary>
        public static string EnableCamera {
            get {
                return ResourceManager.GetString("EnableCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again later..
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort account recover failed..
        /// </summary>
        public static string EscortAccountRecoverFailed {
            get {
                return ResourceManager.GetString("EscortAccountRecoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort account activated successfully..
        /// </summary>
        public static string EscortActivated {
            get {
                return ResourceManager.GetString("EscortActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort account activation failed..
        /// </summary>
        public static string EscortActivateFailed {
            get {
                return ResourceManager.GetString("EscortActivateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort account deactivated successfully..
        /// </summary>
        public static string EscortDeactivate {
            get {
                return ResourceManager.GetString("EscortDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort account deactivation failed..
        /// </summary>
        public static string EscortDeactivateFailed {
            get {
                return ResourceManager.GetString("EscortDeactivateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort account delete failed..
        /// </summary>
        public static string EscortDeleteFailed {
            get {
                return ResourceManager.GetString("EscortDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Escort deleted successfully..
        /// </summary>
        public static string EscortDeleteSuccess {
            get {
                return ResourceManager.GetString("EscortDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment account activated successfully..
        /// </summary>
        public static string EstablishmentActivated {
            get {
                return ResourceManager.GetString("EstablishmentActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment account activation failed..
        /// </summary>
        public static string EstablishmentActivationFailed {
            get {
                return ResourceManager.GetString("EstablishmentActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment account and it&apos;s realated escort account&apos;s deactivated successfully..
        /// </summary>
        public static string EstablishmentDeActivated {
            get {
                return ResourceManager.GetString("EstablishmentDeActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishment account deactivation failed..
        /// </summary>
        public static string EstablishmentDeActivationFailed {
            get {
                return ResourceManager.GetString("EstablishmentDeActivationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add more escorts, please upgrade your subscription..
        /// </summary>
        public static string EstablishmentEscortLimitExceeded {
            get {
                return ResourceManager.GetString("EstablishmentEscortLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to purchase subscription for this service..
        /// </summary>
        public static string EstablishmentSubscriptionNotExists {
            get {
                return ResourceManager.GetString("EstablishmentSubscriptionNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription failed..
        /// </summary>
        public static string FailedSubscription {
            get {
                return ResourceManager.GetString("FailedSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to cancel the current subscription..
        /// </summary>
        public static string FailedToCancelSubscription {
            get {
                return ResourceManager.GetString("FailedToCancelSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password failed..
        /// </summary>
        public static string FailedToSetNewPassword {
            get {
                return ResourceManager.GetString("FailedToSetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name is required..
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password mail has been sent to your registered email address..
        /// </summary>
        public static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forget Password.
        /// </summary>
        public static string ForgetPasswordSubject {
            get {
                return ResourceManager.GetString("ForgetPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A reset password request has already been submitted, and an email has been sent to your registered email address within the last 30 minutes..
        /// </summary>
        public static string ForgotEmailAlreadySent {
            get {
                return ResourceManager.GetString("ForgotEmailAlreadySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender is required..
        /// </summary>
        public static string GenderRequired {
            get {
                return ResourceManager.GetString("GenderRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details get successfully..
        /// </summary>
        public static string GetUserDetails {
            get {
                return ResourceManager.GetString("GetUserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is invalid..
        /// </summary>
        public static string InvalidConfirmationToken {
            get {
                return ResourceManager.GetString("InvalidConfirmationToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request or reset password token has been expired..
        /// </summary>
        public static string InvalidOrResetTokenExpired {
            get {
                return ResourceManager.GetString("InvalidOrResetTokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid request..
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid verification code.
        /// </summary>
        public static string InvalidVerificationCode {
            get {
                return ResourceManager.GetString("InvalidVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JWT authorization token is required..
        /// </summary>
        public static string JWTtokenRequired {
            get {
                return ResourceManager.GetString("JWTtokenRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name is required..
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have login successfully..
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logout successfully..
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout successfully.
        /// </summary>
        public static string LogoutSuccess {
            get {
                return ResourceManager.GetString("LogoutSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark favorites Successfully..
        /// </summary>
        public static string MarkFavoritesSuccess {
            get {
                return ResourceManager.GetString("MarkFavoritesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name legth must be between 3 and 100 characters..
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password is required..
        /// </summary>
        public static string NewPasswordRequired {
            get {
                return ResourceManager.GetString("NewPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authourize to access..
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version you are using is older, please update with new one..
        /// </summary>
        public static string OldAppVersion {
            get {
                return ResourceManager.GetString("OldAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old and New Password can not be same..
        /// </summary>
        public static string OldNewPasswordNotSame {
            get {
                return ResourceManager.GetString("OldNewPasswordNotSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is required..
        /// </summary>
        public static string OldPasswordRequired {
            get {
                return ResourceManager.GetString("OldPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Updated Successfully, Please login again..
        /// </summary>
        public static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password should be minimum of 6 characters and maximum of 16 characters, including uppercase, lowercase, number and special character(@$!%*?&amp;#)..
        /// </summary>
        public static string PasswordValid {
            get {
                return ResourceManager.GetString("PasswordValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile paused successfully..
        /// </summary>
        public static string PauseProfile {
            get {
                return ResourceManager.GetString("PauseProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status update failed.
        /// </summary>
        public static string PaymentStatusFailed {
            get {
                return ResourceManager.GetString("PaymentStatusFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment status updated successfully.
        /// </summary>
        public static string PaymentStatusUpdated {
            get {
                return ResourceManager.GetString("PaymentStatusUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number length should be minimum 7 and maximum 15..
        /// </summary>
        public static string PhoneNumberLength {
            get {
                return ResourceManager.GetString("PhoneNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number is required..
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Changed.
        /// </summary>
        public static string PlanChanged {
            get {
                return ResourceManager.GetString("PlanChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription Purchased.
        /// </summary>
        public static string PlanPurchased {
            get {
                return ResourceManager.GetString("PlanPurchased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have an active subscription. To delete your profile, you must cancel your subscription first..
        /// </summary>
        public static string ProfileCanNotDeleteDueToActiveSubscription {
            get {
                return ResourceManager.GetString("ProfileCanNotDeleteDueToActiveSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile deleted successfully. .
        /// </summary>
        public static string ProfileDeleted {
            get {
                return ResourceManager.GetString("ProfileDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete profile..
        /// </summary>
        public static string ProfileNotDeleted {
            get {
                return ResourceManager.GetString("ProfileNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile update failed..
        /// </summary>
        public static string ProfileUpdateFailed {
            get {
                return ResourceManager.GetString("ProfileUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updated successfully..
        /// </summary>
        public static string ProfileUpdateSuccess {
            get {
                return ResourceManager.GetString("ProfileUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile published successfully..
        /// </summary>
        public static string PublishProfile {
            get {
                return ResourceManager.GetString("PublishProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription purchased..
        /// </summary>
        public static string PurchaseSubscription {
            get {
                return ResourceManager.GetString("PurchaseSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query length must be between 15 and 500 characters..
        /// </summary>
        public static string QueryLength {
            get {
                return ResourceManager.GetString("QueryLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query is required..
        /// </summary>
        public static string QueryRequired {
            get {
                return ResourceManager.GetString("QueryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to recover this escort account..
        /// </summary>
        public static string RecoverEscort {
            get {
                return ResourceManager.GetString("RecoverEscort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to recover this establishment account..
        /// </summary>
        public static string RecoverEstablishment {
            get {
                return ResourceManager.GetString("RecoverEstablishment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You want to recover this user account..
        /// </summary>
        public static string RecoverUser {
            get {
                return ResourceManager.GetString("RecoverUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistrationSubject {
            get {
                return ResourceManager.GetString("RegistrationSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification link sent successfully.
        /// </summary>
        public static string ResendVerificationLink {
            get {
                return ResourceManager.GetString("ResendVerificationLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification link sent successfully.
        /// </summary>
        public static string ResendVerificationLinkSubject {
            get {
                return ResourceManager.GetString("ResendVerificationLinkSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email verification code has been sent to your email address. Please verify your email address..
        /// </summary>
        public static string SentVerifyCode {
            get {
                return ResourceManager.GetString("SentVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to your email address. Please verify your email address..
        /// </summary>
        public static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User signup failed..
        /// </summary>
        public static string SignUpFailed {
            get {
                return ResourceManager.GetString("SignUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration successfully..
        /// </summary>
        public static string SignUpSuccess {
            get {
                return ResourceManager.GetString("SignUpSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong..
        /// </summary>
        public static string SomethingWrong {
            get {
                return ResourceManager.GetString("SomethingWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subordinate details added successfully..
        /// </summary>
        public static string StaffAdded {
            get {
                return ResourceManager.GetString("StaffAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subordinate details updated successfully..
        /// </summary>
        public static string StaffUpdated {
            get {
                return ResourceManager.GetString("StaffUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription cancel failed..
        /// </summary>
        public static string SubscriptionCancelledError {
            get {
                return ResourceManager.GetString("SubscriptionCancelledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscription cancelled successfully..
        /// </summary>
        public static string SubscriptionCancelledSuccess {
            get {
                return ResourceManager.GetString("SubscriptionCancelledSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment for the subscription to the plan is  failed..
        /// </summary>
        public static string SubscriptionFailed {
            get {
                return ResourceManager.GetString("SubscriptionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your payment for the subscription to the plan is successfull..
        /// </summary>
        public static string SubscriptionSuccess {
            get {
                return ResourceManager.GetString("SubscriptionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token fetched successfully..
        /// </summary>
        public static string TokenFetched {
            get {
                return ResourceManager.GetString("TokenFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deactivated. Please contact admin..
        /// </summary>
        public static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this API..
        /// </summary>
        public static string UnauthorizedMessage {
            get {
                return ResourceManager.GetString("UnauthorizedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to undo favorites Successfully..
        /// </summary>
        public static string UnMarkFavoritesSuccess {
            get {
                return ResourceManager.GetString("UnMarkFavoritesSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile updates failed..
        /// </summary>
        public static string UpdateNotProfile {
            get {
                return ResourceManager.GetString("UpdateNotProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile has been updated successfully..
        /// </summary>
        public static string UpdateProfile {
            get {
                return ResourceManager.GetString("UpdateProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you confirm, your current plan will be cancelled first, and new plan will be activated after payment is confirmed. No refund will be given for the remaining days in the active plan..
        /// </summary>
        public static string UpdateSubscription {
            get {
                return ResourceManager.GetString("UpdateSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been deleted. Please contact to admin..
        /// </summary>
        public static string UserAccountDeleted {
            get {
                return ResourceManager.GetString("UserAccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account recovered successfully..
        /// </summary>
        public static string UserAccountRecovered {
            get {
                return ResourceManager.GetString("UserAccountRecovered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account recover failed..
        /// </summary>
        public static string UserAccountRecoverFailed {
            get {
                return ResourceManager.GetString("UserAccountRecoverFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account activated successfully..
        /// </summary>
        public static string UserActivated {
            get {
                return ResourceManager.GetString("UserActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account activation failed..
        /// </summary>
        public static string UserActivateFailed {
            get {
                return ResourceManager.GetString("UserActivateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account deactivated successfully..
        /// </summary>
        public static string UserDeactivate {
            get {
                return ResourceManager.GetString("UserDeactivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account deactivation failed..
        /// </summary>
        public static string UserDeactivateFailed {
            get {
                return ResourceManager.GetString("UserDeactivateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User account delete failed..
        /// </summary>
        public static string UserDeleteFailed {
            get {
                return ResourceManager.GetString("UserDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleted successfully.
        /// </summary>
        public static string UserDeleteSuccess {
            get {
                return ResourceManager.GetString("UserDeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details not found..
        /// </summary>
        public static string UserDetailsNotFound {
            get {
                return ResourceManager.GetString("UserDetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details updated successfully..
        /// </summary>
        public static string UserDetailUpdated {
            get {
                return ResourceManager.GetString("UserDetailUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User details update failed..
        /// </summary>
        public static string UserDetailUpdateFail {
            get {
                return ResourceManager.GetString("UserDetailUpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already exists..
        /// </summary>
        public static string UserExists {
            get {
                return ResourceManager.GetString("UserExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is currently inactive. If you need assistance, please reach out to the support team..
        /// </summary>
        public static string UserIsNotActive {
            get {
                return ResourceManager.GetString("UserIsNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is currently not approved by admin. If you need assistance, please reach out to the support team..
        /// </summary>
        public static string UserIsNotApprove {
            get {
                return ResourceManager.GetString("UserIsNotApprove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User list fected successfully..
        /// </summary>
        public static string UserListFetchedSucessfully {
            get {
                return ResourceManager.GetString("UserListFetchedSucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User does not exist..
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UtcOffset In Second is required..
        /// </summary>
        public static string UtcOffsetInSecond {
            get {
                return ResourceManager.GetString("UtcOffsetInSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification link sent to your registered mail Id, please click on the link and verify you email..
        /// </summary>
        public static string VerificationLinkSent {
            get {
                return ResourceManager.GetString("VerificationLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email verification link sent failed, please try again..
        /// </summary>
        public static string VerificationLinkSentFailed {
            get {
                return ResourceManager.GetString("VerificationLinkSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify Email.
        /// </summary>
        public static string VerifyEmailSubject {
            get {
                return ResourceManager.GetString("VerifyEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you haven’t already, kindly subscribe to any of our packages to unlock full access. If you’ve already subscribed, please disregard this message..
        /// </summary>
        public static string WelcomeEmailMessage {
            get {
                return ResourceManager.GetString("WelcomeEmailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password is wrong..
        /// </summary>
        public static string WrongOldPassword {
            get {
                return ResourceManager.GetString("WrongOldPassword", resourceCulture);
            }
        }
    }
}
